[tool.black]
line-length = 120
exclude = '''
/(
      \.eggs
    | \.git
    | \.mypy_cache
    | venv
  )/
'''

[tool.isort]
profile = "black"
multi_line_output = 3
include_trailing_comma = true
lines_after_imports = 2
skip_gitignore = true
virtual_env = "venv"
skip = "__init__.py"